spring:
  profiles:
    active: dev # Activate the 'dev' profile by default

  servlet:
    multipart:
      max-file-size: 50MB # Set maximum file upload size to 50MB

  # SpringDoc (OpenAPI) configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    doc-expansion: none
  api-docs:
    path: /v3/api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

server:
  servlet:
    context-path: /api/v1/ # Set the base context path for the application