spring:
  profiles:
    active: dev # Activate the 'dev' profile by default

  servlet:
    multipart:
      max-file-size: 50MB # Set maximum file upload size to 50MB

  # SpringDoc (OpenAPI) configuration
  springdoc:
    default-consumes-media-type: application/json # Set default media type for requests

server:
  servlet:
    context-path: /api/v1/ # Set the base context path for the application